### ISSUE TITLE
推理阶段指标计算问题

### ISSUE THREAD

**Issue by JeremyChou28** [chenxiaodanhit/BiTGraph#2]
您好，非常感谢您的工作。
有个细节想请问下，您这个工作是考虑不完整数据输入下的预测问题。
在训练阶段，您假设的是只有horizon window的观测部分能获取并作为监督信号，包括在验证集上也是
但是推理阶段，您是能有整段预测序列的groundtruth，来计算最终的预测性能。
请问为什么推理阶段不跟前面一致呢？从您的dataloader处理来看，应该是一开始对整个数据集就制造了缺失，那么对于测试集应该也是有缺失的，所以对于预测的y和真实y计算性能指标时应该也只能在观测位置进行计算吧？
期待您的回复，谢谢。

**Comment by chenxiaodanhit** [comment]
您好，非常感谢您对我们的工作感兴趣，真实世界中数据缺失一致，训练和验证都只用观测部分，测试阶段，当然也可以和训练验证一样只用观测ground truth计算指标，但是为了更完整的评测模型的能力，我们用到了所有的数据，因为模拟缺失的部分我们也有真实的观测结果。

**Comment by chenxiaodanhit** [comment]
您好，非常感谢您对我们的工作感兴趣，真实世界中数据缺失一致，训练和验证都只用观测部分，测试阶段，当然也可以和训练验证一样只用观测ground truth计算指标，但是我们的目标是带缺失数据的预测，所以期待模型在有缺失的情况下仍然可以对未来窗口有完整的准确的预测结果，因此为了评测模型的带缺失预测能力，我们用到了所有的数据，因为模拟缺失的部分我们也有真实的观测结果。

**Comment by JeremyChou28** [comment]
好的，谢谢
